#!/bin/bash

usage="Usage: batl [ info | stake | latest | dust ] \n \n
	info: Check basic info. \n
	stake: Enables staking; Passes password without storing it in memory. \n
	dust: Prunes dust from wallet. Dust is defined as less than .0001BATL. Requires jq. \n"

blkc='/usr/local/bin/batlnext-cli -datadir=/var/lib/.batlnext/'

case $1 in

info )
	$blkc getwalletinfo | egrep "balance|staked_balance|txcount|unconfirmed_balance|immature_balance|total_balance";
	$blkc getnetworkinfo | egrep "subversion|connections";
	$blkc getinfo | egrep "blocks";
	$blkc getblockchaininfo | egrep "best";
	$blkc getstakinginfo | egrep "enabled|staking|netstakeweight|expectedtime";
;;	

stake )
	echo 'enter BattlestarCoin Password'
	read -s BLKPW
	$blkc walletpassphrase $BLKPW 99999999 true
	BLKPW=null
;;

dust )
	IFS=$'\n';

	 /usr/local/bin/batlnext-cli -datadir=/var/lib/.batlnext/ listtransactions "*" 99999 | jq -r '.[] | select(.category != "send") | select(.amount < .0001) | .txid' | uniq >txid.txt

	while read line; do
	        echo $line 
	        /usr/local/bin/batlnext-cli -datadir=/var/lib/.batlnext/ removeprunedfunds $(echo $line)
	done < "txid.txt"
;;

*)
    echo -e $usage
;;	

esac
